# -*- mode: ruby -*-
# vi: set ft=ruby :

# This vagrantfile creates a VM with the development environment
# configured and ready to go.
#
# The setup script (env var $script) in this file installs docker.
# This is not in the setup.sh file because the docker install needs
# to be secure when running on a real linux machine.
# The docker environment that is installed by this script is not secure,
# it depends on the host being secure.
#
# At the end of the setup script in this file, a call is made
# to run setup.sh to create the developer environment.

# This is the mount point for the sync_folders of the source
SRCMOUNT = "/home/vagrant/gopath/src/github.com/leochan007/xtp.go"
LOCALDEV = "/local-dev"

$script = <<SCRIPT
set -x

cd #{SRCMOUNT}/devenv
chmod +x setup.sh
./setup.sh
#source /home/ubuntu/.bashrc

SCRIPT

#baseimage_release = File.read '../.baseimage-release'

Vagrant.require_version ">= 1.7.4"
Vagrant.configure('2') do |config|
  config.vm.box = "generic/centos7"
  #config.vm.box = "ubuntu/xenial64"
  #config.vm.box_version = ENV['USE_LOCAL_BASEIMAGE'] ? "0": baseimage_release # Vagrant does not support versioning local images, the local version is always implicitly version 0

  config.vm.network :forwarded_port, guest: 8341, host: 8341
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 16060, host: 16060
  #config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

  config.vm.synced_folder "..", "#{SRCMOUNT}"
  #, :mount_options => ["dmode=755","fmode=644"]
  #config.vm.synced_folder ENV.fetch('LOCALDEVDIR', ".."), "#{LOCALDEV}"

  config.vm.provider :virtualbox do |vb|
    vb.name = "go_xtp_dev"
    vb.customize ['modifyvm', :id, '--memory', '4096']
    vb.cpus = 2

  end

  config.vm.provision :shell, inline: $script
end
